[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile", "yarn global add ts-node typescript"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start"
